-- Reality Engine V4 caller-memory schema
-- Run once in the Supabase SQL editor for the project used by the Android app.

create table if not exists public.caller_profiles (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    phone_key text not null,
    display_name text not null default '',
    profile jsonb not null default '{}'::jsonb,
    updated_at_ms bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (owner_id, phone_key)
);

alter table public.caller_profiles enable row level security;

revoke all on table public.caller_profiles from anon;
grant select, insert, update, delete on table public.caller_profiles to authenticated;
grant usage, select on sequence public.caller_profiles_id_seq to authenticated;

create policy "caller_profiles_select_own"
on public.caller_profiles
for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy "caller_profiles_insert_own"
on public.caller_profiles
for insert
to authenticated
with check ((select auth.uid()) = owner_id);

create policy "caller_profiles_update_own"
on public.caller_profiles
for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "caller_profiles_delete_own"
on public.caller_profiles
for delete
to authenticated
using ((select auth.uid()) = owner_id);

comment on table public.caller_profiles is
'Reality Engine local-first caller memory. Audio recordings are intentionally not stored here.';
