package com.realityengine.v4

import android.Manifest
import android.app.Activity
import android.app.role.RoleManager
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.database.Cursor
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.provider.CallLog
import android.provider.ContactsContract
import android.provider.Settings
import android.telecom.TelecomManager
import android.view.Gravity
import android.view.View
import android.widget.*

class MainActivity : Activity() {
    private lateinit var status:TextView;private lateinit var shizukuStatus:TextView;private lateinit var audioStatus:TextView;private lateinit var number:EditText;private lateinit var error:TextView;private lateinit var content:LinearLayout
    private var screen="DIAL"
    private val bg=Color.rgb(3,7,12);private val panel=Color.rgb(9,18,27);private val soft=Color.rgb(13,27,39);private val cyan=Color.rgb(40,224,255);private val magenta=Color.rgb(255,55,190);private val green=Color.rgb(75,255,165);private val muted=Color.rgb(118,147,163)
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);buildPhoneUi()}
    override fun onResume(){super.onResume();if(::status.isInitialized){updateRoleStatus();updateShizukuStatus();updateAudioStatus()}}
    override fun onBackPressed(){if(screen!="DIAL")showPhone() else super.onBackPressed()}
    private fun neon(fill:Int=panel,stroke:Int=cyan,r:Float=16f)=GradientDrawable().apply{setColor(fill);setStroke(1.dp(),stroke);cornerRadius=r.dpF()}
    private fun cyberButton(label:String,click:()->Unit)=Button(this).apply{text=label;textSize=12f;letterSpacing=.12f;setTextColor(cyan);typeface=Typeface.create(Typeface.MONOSPACE,Typeface.BOLD);background=neon(soft,Color.rgb(24,91,111),14f);setOnClickListener{click()};stateListAnimator=null}
    private fun buildPhoneUi(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(18.dp(),16.dp(),18.dp(),10.dp());setBackgroundColor(bg)};val utility=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};status=TextView(this).apply{textSize=11f;letterSpacing=.14f;setTextColor(green);typeface=Typeface.MONOSPACE;gravity=Gravity.CENTER_VERTICAL};utility.addView(status,LinearLayout.LayoutParams(0,46.dp(),1f));utility.addView(cyberButton("// SETTINGS"){showSettings()},LinearLayout.LayoutParams(132.dp(),46.dp()));root.addView(utility);root.addView(View(this).apply{setBackgroundColor(Color.rgb(18,75,91))},LinearLayout.LayoutParams(-1,1.dp()).apply{setMargins(0,4.dp(),0,8.dp())});shizukuStatus=TextView(this).apply{visibility=View.GONE};audioStatus=TextView(this).apply{visibility=View.GONE};root.addView(shizukuStatus);root.addView(audioStatus);val scroll=ScrollView(this).apply{isFillViewport=true};content=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.TOP};scroll.addView(content);root.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));val nav=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setPadding(0,8.dp(),0,0)};nav.addView(cyberButton("DIAL"){showPhone()},LinearLayout.LayoutParams(0,52.dp(),1f).apply{setMargins(3.dp(),0,3.dp(),0)});nav.addView(cyberButton("TRAFFIC"){showRecents()},LinearLayout.LayoutParams(0,52.dp(),1f).apply{setMargins(3.dp(),0,3.dp(),0)});nav.addView(cyberButton("INDEX"){showContacts()},LinearLayout.LayoutParams(0,52.dp(),1f).apply{setMargins(3.dp(),0,3.dp(),0)});root.addView(nav);setContentView(root);updateRoleStatus();updateShizukuStatus();updateAudioStatus();showPhone()}
    private fun showPhone(){screen="DIAL";content.removeAllViews();content.gravity=Gravity.BOTTOM;val deck=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.BOTTOM};deck.addView(TextView(this).apply{text="// SECURE DIAL";textSize=11f;letterSpacing=.18f;setTextColor(magenta);typeface=Typeface.MONOSPACE;setPadding(4.dp(),14.dp(),0,2.dp())});number=EditText(this).apply{hint="_ _ _  _ _ _  _ _ _ _";setHintTextColor(Color.rgb(54,83,98));setTextColor(cyan);textSize=29f;letterSpacing=.06f;typeface=Typeface.MONOSPACE;gravity=Gravity.CENTER;background=neon(Color.rgb(5,12,19),Color.rgb(18,88,107),10f);inputType=android.text.InputType.TYPE_CLASS_PHONE;isSingleLine=true};deck.addView(number,LinearLayout.LayoutParams(-1,70.dp()).apply{setMargins(0,8.dp(),0,12.dp())});val grid=GridLayout(this).apply{columnCount=3;rowCount=4;alignmentMode=GridLayout.ALIGN_BOUNDS;useDefaultMargins=false};val keys=arrayOf("1","2","3","4","5","6","7","8","9","*","0","#");keys.forEach{key->val b=Button(this).apply{text=key;textSize=23f;setTextColor(cyan);typeface=Typeface.MONOSPACE;background=neon(panel,Color.rgb(20,88,108),18f);stateListAnimator=null;setOnClickListener{number.append(key)}};grid.addView(b,GridLayout.LayoutParams().apply{width=0;height=68.dp();columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);setMargins(6.dp(),6.dp(),6.dp(),6.dp())})};deck.addView(grid);val actions=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setPadding(0,12.dp(),0,0)};actions.addView(cyberButton("DEL"){val t=number.text;if(t.isNotEmpty())t.delete(t.length-1,t.length)}.apply{setOnLongClickListener{number.text.clear();true}},LinearLayout.LayoutParams(72.dp(),56.dp()).apply{setMargins(4.dp(),0,8.dp(),0)});actions.addView(Button(this).apply{text="CONNECT";textSize=14f;letterSpacing=.15f;setTextColor(Color.rgb(0,25,30));typeface=Typeface.create(Typeface.MONOSPACE,Typeface.BOLD);background=neon(cyan,cyan,18f);stateListAnimator=null;setOnClickListener{placeCall(number.text.toString().trim())}},LinearLayout.LayoutParams(0,56.dp(),1f).apply{setMargins(8.dp(),0,4.dp(),0)});deck.addView(actions);error=TextView(this).apply{textSize=12f;setTextColor(magenta);typeface=Typeface.MONOSPACE;gravity=Gravity.CENTER;setPadding(0,10.dp(),0,0)};deck.addView(error);content.addView(deck,LinearLayout.LayoutParams(-1,-1))}
    private fun showRecents(){screen="TRAFFIC";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("TRAFFIC");if(checkSelfPermission(Manifest.permission.READ_CALL_LOG)!=PackageManager.PERMISSION_GRANTED){content.addView(cyberButton("AUTHORIZE CALL HISTORY"){requestPermissions(arrayOf(Manifest.permission.READ_CALL_LOG),REQ_CALL_LOG)});return};val c:Cursor?=contentResolver.query(CallLog.Calls.CONTENT_URI,arrayOf(CallLog.Calls.NUMBER,CallLog.Calls.CACHED_NAME,CallLog.Calls.TYPE,CallLog.Calls.DURATION),null,null,"${CallLog.Calls.DATE} DESC");c?.use{var count=0;while(it.moveToNext()&&count<30){val n=it.getString(0)?:"Unknown";val cached=it.getString(1);val display=cached?.takeIf{s->s.isNotBlank()}?:resolveContactName(n)?:n;val type=when(it.getInt(2)){CallLog.Calls.INCOMING_TYPE->"IN";CallLog.Calls.OUTGOING_TYPE->"OUT";CallLog.Calls.MISSED_TYPE->"MISSED";else->"CALL"};val dur=it.getLong(3);content.addView(listButton("$display\n$type  •  $n  •  ${dur}s"){openRecent(n)}.apply{setOnLongClickListener{placeCall(n);true}});count++}}}
    private fun resolveContactName(phone:String):String?{if(checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED)return null;return try{val uri=Uri.withAppendedPath(ContactsContract.PhoneLookup.CONTENT_FILTER_URI,Uri.encode(phone));contentResolver.query(uri,arrayOf(ContactsContract.PhoneLookup.DISPLAY_NAME),null,null,null)?.use{c->if(c.moveToFirst())c.getString(0)?.takeIf{it.isNotBlank()}else null}}catch(_:Throwable){null}}
    private fun showContacts(query:String=""){screen="INDEX";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("INDEX");if(checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED){content.addView(cyberButton("AUTHORIZE CONTACTS"){requestPermissions(arrayOf(Manifest.permission.READ_CONTACTS),REQ_CONTACTS)});return};val search=EditText(this).apply{hint="SEARCH INDEX";setHintTextColor(muted);setTextColor(cyan);setText(query);typeface=Typeface.MONOSPACE;isSingleLine=true;background=neon(panel,Color.rgb(18,88,107),12f);setPadding(16.dp(),0,16.dp(),0)};content.addView(search,LinearLayout.LayoutParams(-1,50.dp()).apply{setMargins(0,0,0,8.dp())});content.addView(cyberButton("EXECUTE SEARCH"){showContacts(search.text.toString().trim())});val sel=if(query.isBlank())null else "${ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME} LIKE ? OR ${ContactsContract.CommonDataKinds.Phone.NUMBER} LIKE ?";val args=if(query.isBlank())null else arrayOf("%$query%","%$query%");contentResolver.query(ContactsContract.CommonDataKinds.Phone.CONTENT_URI,arrayOf(ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME,ContactsContract.CommonDataKinds.Phone.NUMBER),sel,args,ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME+" ASC")?.use{var count=0;while(it.moveToNext()&&count<100){val name=it.getString(0)?:"Unknown";val phone=it.getString(1)?:"";content.addView(listButton("$name\n$phone"){numberFromContact(phone)}.apply{setOnLongClickListener{placeCall(phone);true}});count++}}}
    private fun showSettings(){screen="SETTINGS";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("SYSTEM // SETTINGS");content.addView(settingCard("DEFAULT DIALER",status.text.toString()){requestDefaultPhoneRole()});content.addView(settingCard("SHIZUKU AUDIO",shizukuStatus.text.toString()){requestShizuku()});content.addView(settingCard("CALL AUDIO",audioStatus.text.toString()){checkCallAudio()});content.addView(settingCard("ANDROID PHONE SETTINGS","Manage system calling apps"){startActivity(Intent(Settings.ACTION_MANAGE_DEFAULT_APPS_SETTINGS))})}
    private fun sectionTitle(t:String){content.addView(TextView(this).apply{text="// $t";textSize=20f;letterSpacing=.10f;setTextColor(cyan);typeface=Typeface.create(Typeface.MONOSPACE,Typeface.BOLD);setPadding(2.dp(),18.dp(),0,16.dp())})}
    private fun listButton(label:String,click:()->Unit)=Button(this).apply{text=label;textSize=14f;gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.rgb(205,241,248));typeface=Typeface.MONOSPACE;background=neon(panel,Color.rgb(15,66,81),10f);stateListAnimator=null;setPadding(16.dp(),0,16.dp(),0);setOnClickListener{click()}}.also{it.layoutParams=LinearLayout.LayoutParams(-1,70.dp()).apply{setMargins(0,4.dp(),0,4.dp())}}
    private fun settingCard(title:String,sub:String,click:()->Unit)=Button(this).apply{text="$title\n$sub";textSize=13f;letterSpacing=.04f;gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(cyan);typeface=Typeface.MONOSPACE;background=neon(panel,Color.rgb(20,78,94),10f);stateListAnimator=null;setPadding(16.dp(),0,16.dp(),0);setOnClickListener{click()}}.also{it.layoutParams=LinearLayout.LayoutParams(-1,76.dp()).apply{setMargins(0,5.dp(),0,5.dp())}}
    private fun updateShizukuStatus(){shizukuStatus.text=when{!ShizukuAudioStatus.binderAvailable()->"OFFLINE";!ShizukuAudioStatus.permissionGranted()->"AUTH REQUIRED";else->"CONNECTED"}}
    private fun updateAudioStatus(){audioStatus.text=when(CallAudioBridge.state(this)){CallAudioBridge.State.UNAVAILABLE->"WAITING FOR SHIZUKU";CallAudioBridge.State.SHIZUKU_READY->"SHIZUKU READY";CallAudioBridge.State.MICROPHONE_PERMISSION_REQUIRED->"MIC AUTH REQUIRED";CallAudioBridge.State.VOICE_CALL_SOURCE_AVAILABLE->"VOICE_CALL AVAILABLE";CallAudioBridge.State.VOICE_CALL_SOURCE_BLOCKED->"VOICE_CALL BLOCKED"}}
    private fun checkCallAudio(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.RECORD_AUDIO),REQ_AUDIO);return};updateAudioStatus();showSettings()}
    private fun requestShizuku(){if(ShizukuAudioStatus.binderAvailable()&&!ShizukuAudioStatus.permissionGranted())ShizukuAudioStatus.requestPermission();updateShizukuStatus();updateAudioStatus();showSettings()}
    private fun openRecent(phone:String){showPhone();number.setText(phone);number.setSelection(number.length())}
    private fun numberFromContact(phone:String){showPhone();number.setText(phone);number.setSelection(number.length())}
    private fun updateRoleStatus(){val t=getSystemService(Context.TELECOM_SERVICE) as TelecomManager;status.text=if(t.defaultDialerPackage==packageName)"● SYSTEM READY" else "● DIALER AUTH REQUIRED"}
    private fun requestDefaultPhoneRole(){val r=getSystemService(RoleManager::class.java);if(r!=null&&r.isRoleAvailable(RoleManager.ROLE_DIALER)&&!r.isRoleHeld(RoleManager.ROLE_DIALER))startActivityForResult(r.createRequestRoleIntent(RoleManager.ROLE_DIALER),REQ_ROLE)else updateRoleStatus()}
    private fun placeCall(v:String){if(v.isEmpty()){if(::error.isInitialized)error.text="NO TARGET NUMBER";return};val t=getSystemService(Context.TELECOM_SERVICE) as TelecomManager;if(t.defaultDialerPackage!=packageName){if(::error.isInitialized)error.text="DEFAULT DIALER AUTH REQUIRED";return};if(checkSelfPermission(Manifest.permission.CALL_PHONE)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.CALL_PHONE),REQ_CALL);return};try{t.placeCall(Uri.fromParts("tel",v,null),null)}catch(e:Exception){if(::error.isInitialized)error.text="CONNECTION FAILED"}}
    override fun onRequestPermissionsResult(rc:Int,p:Array<out String>,g:IntArray){super.onRequestPermissionsResult(rc,p,g);when(rc){REQ_CALL->if(g.firstOrNull()==PackageManager.PERMISSION_GRANTED&&::number.isInitialized)placeCall(number.text.toString().trim());REQ_CALL_LOG->showRecents();REQ_CONTACTS->showContacts();REQ_AUDIO->{updateAudioStatus();showSettings()}}}
    private fun Int.dp()=(this*resources.displayMetrics.density).toInt();private fun Float.dpF()=this*resources.displayMetrics.density
    companion object{private const val REQ_ROLE=1001;private const val REQ_CALL=1002;private const val REQ_CALL_LOG=1003;private const val REQ_CONTACTS=1004;private const val REQ_AUDIO=1005}
}
