package com.realityengine.v4

import android.Manifest
import android.app.Activity
import android.app.AlertDialog
import android.app.role.RoleManager
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.provider.Settings
import android.telecom.TelecomManager
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.*

class MainActivity : Activity() {
    private lateinit var status:TextView;private lateinit var shizukuStatus:TextView;private lateinit var audioStatus:TextView;private lateinit var number:EditText;private lateinit var contactMatch:TextView;private lateinit var error:TextView;private lateinit var content:LinearLayout;private lateinit var nav:LinearLayout
    private lateinit var contactIndex:ContactIndex;private lateinit var callHistory:CallHistoryIndex;private lateinit var settingsStore:SettingsStore
    private var dialScreen:DialScreen?=null
    private var screen="DIAL";private var buttonShape=1
    private val bg=Color.rgb(3,7,12);private val panel=Color.rgb(9,18,27);private val soft=Color.rgb(13,27,39);private val cyan=Color.rgb(40,224,255);private val green=Color.rgb(75,255,165);private val muted=Color.rgb(118,147,163)
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);contactIndex=ContactIndex(this);callHistory=CallHistoryIndex(this,contactIndex);settingsStore=SettingsStore(this);buttonShape=getPreferences(MODE_PRIVATE).getInt("buttonShape",1);buildPhoneUi()}
    override fun onResume(){super.onResume();if(::status.isInitialized){updateRoleStatus();updateShizukuStatus();updateAudioStatus()}}
    override fun onBackPressed(){if(screen!="DIAL")showPhone() else super.onBackPressed()}
    private fun radius()=when(buttonShape){0->3f;2->30f;else->14f}
    private fun neon(fill:Int=panel,stroke:Int=cyan,r:Float=radius())=GradientDrawable().apply{setColor(fill);setStroke(1.dp(),stroke);cornerRadius=r.dpF()}
    private fun cyberButton(label:String,click:()->Unit)=Button(this).apply{text=label;setTextColor(cyan);RealityTypography.technical(this,12f);background=neon(soft,Color.rgb(24,91,111));setOnClickListener{click()};stateListAnimator=null}
    private fun navItem(icon:String,label:String,target:String,click:()->Unit):LinearLayout{val active=screen==target;return LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(3.dp(),2.dp(),3.dp(),2.dp());addView(TextView(this@MainActivity).apply{text=icon;gravity=Gravity.CENTER;setTextColor(if(active)Color.rgb(0,28,34) else muted);RealityTypography.displayMedium(this,18f);background=if(active)neon(cyan,cyan,22f) else null},LinearLayout.LayoutParams(54.dp(),28.dp()));addView(TextView(this@MainActivity).apply{text=label;gravity=Gravity.CENTER;setTextColor(if(active)cyan else muted);RealityTypography.technical(this,9f)},LinearLayout.LayoutParams(-1,20.dp()));setOnClickListener{click()}}}
    private fun refreshNav(){if(!::nav.isInitialized)return;nav.removeAllViews();nav.addView(navItem("☎","Phone","DIAL"){showPhone()},LinearLayout.LayoutParams(0,54.dp(),1f));nav.addView(navItem("◴","Traffic","TRAFFIC"){showRecents()},LinearLayout.LayoutParams(0,54.dp(),1f));nav.addView(navItem("▣","Index","INDEX"){showContacts()},LinearLayout.LayoutParams(0,54.dp(),1f));nav.addView(navItem("⚙","Settings","SETTINGS"){showSettings()},LinearLayout.LayoutParams(0,54.dp(),1f))}
    private fun buildPhoneUi(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(18.dp(),34.dp(),18.dp(),8.dp());setBackgroundColor(bg)};val utility=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};status=TextView(this).apply{setTextColor(green);gravity=Gravity.CENTER_VERTICAL;RealityTypography.signal(this,11f)};utility.addView(status,LinearLayout.LayoutParams(0,42.dp(),1f));root.addView(utility);root.addView(View(this).apply{setBackgroundColor(Color.rgb(18,75,91))},LinearLayout.LayoutParams(-1,1.dp()).apply{setMargins(0,2.dp(),0,4.dp())});shizukuStatus=TextView(this).apply{visibility=View.GONE};audioStatus=TextView(this).apply{visibility=View.GONE};root.addView(shizukuStatus);root.addView(audioStatus);val scroll=ScrollView(this).apply{isFillViewport=true};content=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.TOP};scroll.addView(content);root.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));nav=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setPadding(0,4.dp(),0,0)};root.addView(nav,LinearLayout.LayoutParams(-1,58.dp()));setContentView(root);updateRoleStatus();updateShizukuStatus();updateAudioStatus();showPhone()}
    private fun showPhone(){screen="DIAL";content.removeAllViews();content.gravity=Gravity.BOTTOM;val dial=DialScreen(this,contactIndex){placeCall(it)};dialScreen=dial;number=dial.number;contactMatch=dial.contactMatch;error=dial.error;content.addView(dial.build(),LinearLayout.LayoutParams(-1,-1));refreshNav()}
    private fun showRecents(){screen="TRAFFIC";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("Traffic");if(!callHistory.hasPermission()){content.addView(cyberButton("Authorize call history"){requestPermissions(arrayOf(Manifest.permission.READ_CALL_LOG),REQ_CALL_LOG)});refreshNav();return};callHistory.recent().forEach{entry->content.addView(listButton("${entry.displayName}\n${entry.direction}  •  ${entry.number}  •  ${entry.durationSeconds}s"){openRecent(entry.number)}.apply{setOnLongClickListener{placeCall(entry.number);true}})};refreshNav()}
    private fun showContacts(query:String=""){screen="INDEX";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("Index");if(checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED){content.addView(cyberButton("Authorize contacts"){requestPermissions(arrayOf(Manifest.permission.READ_CONTACTS),REQ_CONTACTS)});refreshNav();return};val search=EditText(this).apply{hint="Search contacts";setHintTextColor(muted);setTextColor(Color.rgb(222,244,248));setText(query);isSingleLine=true;background=neon(panel,Color.rgb(18,88,107));setPadding(16.dp(),0,16.dp(),0);RealityTypography.display(this,16f)};content.addView(search,LinearLayout.LayoutParams(-1,52.dp()).apply{setMargins(0,0,0,10.dp())});content.addView(cyberButton("Search"){showContacts(search.text.toString().trim())});contactIndex.search(query).forEach{contact->content.addView(listButton("${contact.name}\n${contact.number}"){numberFromContact(contact.number)}.apply{setOnLongClickListener{placeCall(contact.number);true}})};refreshNav()}
    private fun showSettings(){screen="SETTINGS";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("Settings & telephony architecture");content.addView(settingCard("Groq",if(settingsStore.groqConfigured()) settingsStore.groqModel else "API key required"){editSecret("Groq API key",settingsStore.groqApiKey){settingsStore.groqApiKey=it}});content.addView(settingCard("Deepgram",if(settingsStore.deepgramConfigured()) settingsStore.deepgramModel else "API key required"){editSecret("Deepgram API key",settingsStore.deepgramApiKey){settingsStore.deepgramApiKey=it}});content.addView(settingCard("Supabase caller profiles",if(settingsStore.supabaseConfigured()) "Configured" else "Configuration required"){editTextValue("Supabase URL",settingsStore.supabaseUrl){settingsStore.supabaseUrl=it}});content.addView(settingCard("Response coach",if(settingsStore.responseCoachEnabled) "Enabled" else "Disabled"){settingsStore.responseCoachEnabled=!settingsStore.responseCoachEnabled;showSettings()});content.addView(settingCard("Haptics",if(settingsStore.hapticsEnabled) "Enabled" else "Disabled"){settingsStore.hapticsEnabled=!settingsStore.hapticsEnabled;showSettings()});content.addView(settingCard("Analysis frequency","Every ${settingsStore.analysisFrequencySeconds} seconds"){settingsStore.analysisFrequencySeconds=if(settingsStore.analysisFrequencySeconds>=10)1 else settingsStore.analysisFrequencySeconds+1;showSettings()});content.addView(settingCard("Default phone application",status.text.toString()){requestDefaultPhoneRole()});content.addView(settingCard("Button geometry",shapeName()){cycleButtonShape()});content.addView(settingCard("Shizuku audio",shizukuStatus.text.toString()){requestShizuku()});content.addView(settingCard("Call audio",audioStatus.text.toString()){checkCallAudio()});content.addView(settingCard("Android phone settings","Manage system calling apps"){startActivity(Intent(Settings.ACTION_MANAGE_DEFAULT_APPS_SETTINGS))});refreshNav()}
    private fun editSecret(title:String,current:String,save:(String)->Unit){val input=EditText(this).apply{setText(current);inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD;setSelection(length())};AlertDialog.Builder(this).setTitle(title).setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save"){_,_->save(input.text.toString());showSettings()}.show()}
    private fun editTextValue(title:String,current:String,save:(String)->Unit){val input=EditText(this).apply{setText(current);inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_URI;setSelection(length())};AlertDialog.Builder(this).setTitle(title).setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save"){_,_->save(input.text.toString());showSettings()}.show()}
    private fun shapeName()=when(buttonShape){0->"Angular · 03";2->"Rounded · 30";else->"Tactical · 14"}
    private fun cycleButtonShape(){buttonShape=(buttonShape+1)%3;getPreferences(MODE_PRIVATE).edit().putInt("buttonShape",buttonShape).apply();buildPhoneUi();showSettings()}
    private fun sectionTitle(t:String){content.addView(TextView(this).apply{text=t;setTextColor(Color.rgb(229,249,252));setPadding(2.dp(),20.dp(),0,16.dp());RealityTypography.displayMedium(this,22f)})}
    private fun listButton(label:String,click:()->Unit)=Button(this).apply{text=label;gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.rgb(205,241,248));RealityTypography.display(this,14f);background=neon(panel,Color.rgb(15,66,81));stateListAnimator=null;setPadding(16.dp(),0,16.dp(),0);setOnClickListener{click()}}.also{it.layoutParams=LinearLayout.LayoutParams(-1,70.dp()).apply{setMargins(0,4.dp(),0,4.dp())}}
    private fun settingCard(title:String,sub:String,click:()->Unit)=Button(this).apply{text="$title\n$sub";gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.rgb(218,245,249));background=neon(panel,Color.rgb(20,78,94));stateListAnimator=null;setPadding(18.dp(),0,18.dp(),0);RealityTypography.display(this,14f);setOnClickListener{click()}}.also{it.layoutParams=LinearLayout.LayoutParams(-1,78.dp()).apply{setMargins(0,5.dp(),0,5.dp())}}
    private fun updateShizukuStatus(){shizukuStatus.text=when{!ShizukuAudioStatus.binderAvailable()->"Offline";!ShizukuAudioStatus.permissionGranted()->"Authorization required";else->"Connected"}}
    private fun updateAudioStatus(){audioStatus.text=when(CallAudioBridge.state(this)){CallAudioBridge.State.UNAVAILABLE->"Waiting for Shizuku";CallAudioBridge.State.SHIZUKU_READY->"Shizuku ready";CallAudioBridge.State.MICROPHONE_PERMISSION_REQUIRED->"Microphone authorization required";CallAudioBridge.State.VOICE_CALL_SOURCE_AVAILABLE->"Voice call available";CallAudioBridge.State.VOICE_CALL_SOURCE_BLOCKED->"Voice call blocked"}}
    private fun checkCallAudio(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.RECORD_AUDIO),REQ_AUDIO);return};updateAudioStatus();showSettings()}
    private fun requestShizuku(){if(ShizukuAudioStatus.binderAvailable()&&!ShizukuAudioStatus.permissionGranted())ShizukuAudioStatus.requestPermission();updateShizukuStatus();updateAudioStatus();showSettings()}
    private fun openRecent(phone:String){showPhone();dialScreen?.setNumber(phone)}
    private fun numberFromContact(phone:String){showPhone();dialScreen?.setNumber(phone)}
    private fun updateRoleStatus(){val t=getSystemService(Context.TELECOM_SERVICE) as TelecomManager;status.text=if(t.defaultDialerPackage==packageName)"● Native cellular phone" else "● Default phone app needed"}
    private fun requestDefaultPhoneRole(){val r=getSystemService(RoleManager::class.java);if(r!=null&&r.isRoleAvailable(RoleManager.ROLE_DIALER)&&!r.isRoleHeld(RoleManager.ROLE_DIALER))startActivityForResult(r.createRequestRoleIntent(RoleManager.ROLE_DIALER),REQ_ROLE)else updateRoleStatus()}
    private fun placeCall(v:String){if(v.isEmpty()){if(::error.isInitialized)error.text="No target number";return};val t=getSystemService(Context.TELECOM_SERVICE) as TelecomManager;if(t.defaultDialerPackage==packageName){if(checkSelfPermission(Manifest.permission.CALL_PHONE)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.CALL_PHONE),REQ_CALL);return};try{t.placeCall(Uri.fromParts("tel",v,null),null)}catch(e:Exception){if(::error.isInitialized)error.text="Connection failed"}}else{if(::error.isInitialized)error.text="Default phone app required"}}
    override fun onRequestPermissionsResult(rc:Int,p:Array<out String>,g:IntArray){super.onRequestPermissionsResult(rc,p,g);when(rc){REQ_CALL->if(g.firstOrNull()==PackageManager.PERMISSION_GRANTED&&::number.isInitialized)placeCall(number.text.toString().trim());REQ_CALL_LOG->showRecents();REQ_CONTACTS->showContacts();REQ_AUDIO->{updateAudioStatus();showSettings()}}}
    private fun Int.dp()=(this*resources.displayMetrics.density).toInt();private fun Float.dpF()=this*resources.displayMetrics.density
    companion object{private const val REQ_ROLE=1001;private const val REQ_CALL=1002;private const val REQ_CALL_LOG=1003;private const val REQ_CONTACTS=1004;private const val REQ_AUDIO=1005}
}
