package com.realityengine.v4

import android.Manifest
import android.app.Activity
import android.app.role.RoleManager
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.provider.Settings
import android.telecom.TelecomManager
import android.view.Gravity
import android.view.View
import android.widget.*

class MainActivity : Activity() {
    private lateinit var status:TextView;private lateinit var shizukuStatus:TextView;private lateinit var audioStatus:TextView;private lateinit var number:EditText;private lateinit var contactMatch:TextView;private lateinit var error:TextView;private lateinit var content:LinearLayout
    private lateinit var contactIndex:ContactIndex;private lateinit var callHistory:CallHistoryIndex
    private var dialScreen:DialScreen?=null
    private var screen="DIAL";private var buttonShape=1
    private val bg=Color.rgb(3,7,12);private val panel=Color.rgb(9,18,27);private val soft=Color.rgb(13,27,39);private val cyan=Color.rgb(40,224,255);private val green=Color.rgb(75,255,165);private val muted=Color.rgb(118,147,163)
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);contactIndex=ContactIndex(this);callHistory=CallHistoryIndex(this,contactIndex);buttonShape=getPreferences(MODE_PRIVATE).getInt("buttonShape",1);buildPhoneUi()}
    override fun onResume(){super.onResume();if(::status.isInitialized){updateRoleStatus();updateShizukuStatus();updateAudioStatus()}}
    override fun onBackPressed(){if(screen!="DIAL")showPhone() else super.onBackPressed()}
    private fun radius()=when(buttonShape){0->3f;2->30f;else->14f}
    private fun neon(fill:Int=panel,stroke:Int=cyan,r:Float=radius())=GradientDrawable().apply{setColor(fill);setStroke(1.dp(),stroke);cornerRadius=r.dpF()}
    private fun cyberButton(label:String,click:()->Unit)=Button(this).apply{text=label;setTextColor(cyan);RealityTypography.technical(this,12f);background=neon(soft,Color.rgb(24,91,111));setOnClickListener{click()};stateListAnimator=null}
    private fun buildPhoneUi(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(18.dp(),34.dp(),18.dp(),10.dp());setBackgroundColor(bg)};val utility=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};status=TextView(this).apply{setTextColor(green);gravity=Gravity.CENTER_VERTICAL;RealityTypography.signal(this,11f)};utility.addView(status,LinearLayout.LayoutParams(0,46.dp(),1f));utility.addView(cyberButton("Settings"){showSettings()},LinearLayout.LayoutParams(132.dp(),46.dp()));root.addView(utility);root.addView(View(this).apply{setBackgroundColor(Color.rgb(18,75,91))},LinearLayout.LayoutParams(-1,1.dp()).apply{setMargins(0,4.dp(),0,8.dp())});shizukuStatus=TextView(this).apply{visibility=View.GONE};audioStatus=TextView(this).apply{visibility=View.GONE};root.addView(shizukuStatus);root.addView(audioStatus);val scroll=ScrollView(this).apply{isFillViewport=true};content=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.TOP};scroll.addView(content);root.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));val nav=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setPadding(0,8.dp(),0,0)};nav.addView(cyberButton("Dial"){showPhone()},LinearLayout.LayoutParams(0,52.dp(),1f).apply{setMargins(3.dp(),0,3.dp(),0)});nav.addView(cyberButton("Traffic"){showRecents()},LinearLayout.LayoutParams(0,52.dp(),1f).apply{setMargins(3.dp(),0,3.dp(),0)});nav.addView(cyberButton("Index"){showContacts()},LinearLayout.LayoutParams(0,52.dp(),1f).apply{setMargins(3.dp(),0,3.dp(),0)});root.addView(nav);setContentView(root);updateRoleStatus();updateShizukuStatus();updateAudioStatus();showPhone()}
    private fun showPhone(){screen="DIAL";content.removeAllViews();content.gravity=Gravity.BOTTOM;val dial=DialScreen(this,contactIndex){placeCall(it)};dialScreen=dial;number=dial.number;contactMatch=dial.contactMatch;error=dial.error;content.addView(dial.build(),LinearLayout.LayoutParams(-1,-1))}
    private fun showRecents(){screen="TRAFFIC";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("Traffic");if(!callHistory.hasPermission()){content.addView(cyberButton("Authorize call history"){requestPermissions(arrayOf(Manifest.permission.READ_CALL_LOG),REQ_CALL_LOG)});return};callHistory.recent().forEach{entry->content.addView(listButton("${entry.displayName}\n${entry.direction}  •  ${entry.number}  •  ${entry.durationSeconds}s"){openRecent(entry.number)}.apply{setOnLongClickListener{placeCall(entry.number);true}})}}
    private fun showContacts(query:String=""){screen="INDEX";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("Index");if(checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED){content.addView(cyberButton("Authorize contacts"){requestPermissions(arrayOf(Manifest.permission.READ_CONTACTS),REQ_CONTACTS)});return};val search=EditText(this).apply{hint="Search contacts";setHintTextColor(muted);setTextColor(Color.rgb(222,244,248));setText(query);isSingleLine=true;background=neon(panel,Color.rgb(18,88,107));setPadding(16.dp(),0,16.dp(),0);RealityTypography.display(this,16f)};content.addView(search,LinearLayout.LayoutParams(-1,52.dp()).apply{setMargins(0,0,0,10.dp())});content.addView(cyberButton("Search"){showContacts(search.text.toString().trim())});contactIndex.search(query).forEach{contact->content.addView(listButton("${contact.name}\n${contact.number}"){numberFromContact(contact.number)}.apply{setOnLongClickListener{placeCall(contact.number);true}})}}
    private fun showSettings(){screen="SETTINGS";content.gravity=Gravity.TOP;content.removeAllViews();sectionTitle("Settings");content.addView(settingCard("Button geometry",shapeName()){cycleButtonShape()});content.addView(settingCard("Default dialer",status.text.toString()){requestDefaultPhoneRole()});content.addView(settingCard("Shizuku audio",shizukuStatus.text.toString()){requestShizuku()});content.addView(settingCard("Call audio",audioStatus.text.toString()){checkCallAudio()});content.addView(settingCard("Android phone settings","Manage system calling apps"){startActivity(Intent(Settings.ACTION_MANAGE_DEFAULT_APPS_SETTINGS))})}
    private fun shapeName()=when(buttonShape){0->"Angular · 03";2->"Rounded · 30";else->"Tactical · 14"}
    private fun cycleButtonShape(){buttonShape=(buttonShape+1)%3;getPreferences(MODE_PRIVATE).edit().putInt("buttonShape",buttonShape).apply();buildPhoneUi();showSettings()}
    private fun sectionTitle(t:String){content.addView(TextView(this).apply{text=t;setTextColor(Color.rgb(229,249,252));setPadding(2.dp(),20.dp(),0,16.dp());RealityTypography.displayMedium(this,24f)})}
    private fun listButton(label:String,click:()->Unit)=Button(this).apply{text=label;gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.rgb(205,241,248));RealityTypography.display(this,14f);background=neon(panel,Color.rgb(15,66,81));stateListAnimator=null;setPadding(16.dp(),0,16.dp(),0);setOnClickListener{click()}}.also{it.layoutParams=LinearLayout.LayoutParams(-1,70.dp()).apply{setMargins(0,4.dp(),0,4.dp())}}
    private fun settingCard(title:String,sub:String,click:()->Unit)=Button(this).apply{text="$title\n$sub";gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.rgb(218,245,249));background=neon(panel,Color.rgb(20,78,94));stateListAnimator=null;setPadding(18.dp(),0,18.dp(),0);RealityTypography.display(this,14f);setOnClickListener{click()}}.also{it.layoutParams=LinearLayout.LayoutParams(-1,78.dp()).apply{setMargins(0,5.dp(),0,5.dp())}}
    private fun updateShizukuStatus(){shizukuStatus.text=when{!ShizukuAudioStatus.binderAvailable()->"Offline";!ShizukuAudioStatus.permissionGranted()->"Authorization required";else->"Connected"}}
    private fun updateAudioStatus(){audioStatus.text=when(CallAudioBridge.state(this)){CallAudioBridge.State.UNAVAILABLE->"Waiting for Shizuku";CallAudioBridge.State.SHIZUKU_READY->"Shizuku ready";CallAudioBridge.State.MICROPHONE_PERMISSION_REQUIRED->"Microphone authorization required";CallAudioBridge.State.VOICE_CALL_SOURCE_AVAILABLE->"Voice call available";CallAudioBridge.State.VOICE_CALL_SOURCE_BLOCKED->"Voice call blocked"}}
    private fun checkCallAudio(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.RECORD_AUDIO),REQ_AUDIO);return};updateAudioStatus();showSettings()}
    private fun requestShizuku(){if(ShizukuAudioStatus.binderAvailable()&&!ShizukuAudioStatus.permissionGranted())ShizukuAudioStatus.requestPermission();updateShizukuStatus();updateAudioStatus();showSettings()}
    private fun openRecent(phone:String){showPhone();dialScreen?.setNumber(phone)}
    private fun numberFromContact(phone:String){showPhone();dialScreen?.setNumber(phone)}
    private fun updateRoleStatus(){val t=getSystemService(Context.TELECOM_SERVICE) as TelecomManager;status.text=if(t.defaultDialerPackage==packageName)"● System ready" else "● Dialer authorization required"}
    private fun requestDefaultPhoneRole(){val r=getSystemService(RoleManager::class.java);if(r!=null&&r.isRoleAvailable(RoleManager.ROLE_DIALER)&&!r.isRoleHeld(RoleManager.ROLE_DIALER))startActivityForResult(r.createRequestRoleIntent(RoleManager.ROLE_DIALER),REQ_ROLE)else updateRoleStatus()}
    private fun placeCall(v:String){if(v.isEmpty()){if(::error.isInitialized)error.text="No target number";return};val t=getSystemService(Context.TELECOM_SERVICE) as TelecomManager;if(t.defaultDialerPackage==packageName){if(checkSelfPermission(Manifest.permission.CALL_PHONE)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.CALL_PHONE),REQ_CALL);return};try{t.placeCall(Uri.fromParts("tel",v,null),null)}catch(e:Exception){if(::error.isInitialized)error.text="Connection failed"}}else{if(::error.isInitialized)error.text="Dialer authorization required"}}
    override fun onRequestPermissionsResult(rc:Int,p:Array<out String>,g:IntArray){super.onRequestPermissionsResult(rc,p,g);when(rc){REQ_CALL->if(g.firstOrNull()==PackageManager.PERMISSION_GRANTED&&::number.isInitialized)placeCall(number.text.toString().trim());REQ_CALL_LOG->showRecents();REQ_CONTACTS->showContacts();REQ_AUDIO->{updateAudioStatus();showSettings()}}}
    private fun Int.dp()=(this*resources.displayMetrics.density).toInt();private fun Float.dpF()=this*resources.displayMetrics.density
    companion object{private const val REQ_ROLE=1001;private const val REQ_CALL=1002;private const val REQ_CALL_LOG=1003;private const val REQ_CONTACTS=1004;private const val REQ_AUDIO=1005}
}
